/*
 * generated by Xtext 2.13.0
 */
package de.jpaw.bonaparte.noSQL.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BDslRuntimeModule extends AbstractBDslRuntimeModule {
}
