/*
 * generated by Xtext 2.13.0
 */
package de.jpaw.bonaparte.noSQL.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BDslStandaloneSetup extends BDslStandaloneSetupGenerated {

	def static void doSetup() {
		new BDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
