/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.noSQL.ui.contentassist

import de.jpaw.bonaparte.noSQL.ui.contentassist.AbstractBDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BDslProposalProvider extends AbstractBDslProposalProvider {
}
