/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BonScriptRuntimeModule extends de.jpaw.bonaparte.dsl.AbstractBonScriptRuntimeModule {

}
