/*
 * generated by Xtext 2.12.0
 */
package de.jpaw.bonaparte.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BonScriptStandaloneSetup extends BonScriptStandaloneSetupGenerated {

	def static void doSetup() {
		new BonScriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
