/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dsl;

import org.apache.log4j.Logger;

import de.jpaw.bonaparte.dsl.generator.CommentConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BonScriptRuntimeModule extends de.jpaw.bonaparte.dsl.AbstractBonScriptRuntimeModule {
    private static Logger LOGGER = Logger.getLogger(BonScriptRuntimeModule.class);
    public BonScriptRuntimeModule() {
        LOGGER.info("BON Runtime module constructed");
    }


    @Override
    public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
        LOGGER.info("BON Value converter bound");
        return CommentConverter.class;
    }
}
