/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.noSQL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDslRuntimeModule extends de.jpaw.bonaparte.noSQL.AbstractBDslRuntimeModule {

}
