/*
 * generated by Xtext
 */
package de.jpaw.persistence.dsl;

import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;

import de.jpaw.persistence.dsl.scoping.BDDLScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDDLRuntimeModule extends de.jpaw.persistence.dsl.AbstractBDDLRuntimeModule {
	// must bind my subclass of ImportedNamespaceAwareScopeProvider here!
	// for implicit importedNamespace
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return BDDLScopeProvider.class;
	}
	
	// bind global scope provider for importURI
	/*
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return ImportUriGlobalScopeProvider.class;
	} */
}
