/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dts.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BDtsUiModule extends de.jpaw.bonaparte.dts.dsl.ui.AbstractBDtsUiModule {
	public BDtsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
