/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.noSQL.dsl.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class BDslScopeProvider extends de.jpaw.bonaparte.dsl.scoping.BonScriptScopeProvider {

}
