/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.noSQL.dsl.validation

import de.jpaw.bonaparte.noSQL.dsl.bDsl.EntityDefinition
import org.eclipse.xtext.validation.Check
import de.jpaw.bonaparte.noSQL.dsl.bDsl.StorageProvider
import de.jpaw.bonaparte.noSQL.dsl.bDsl.BDslPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BDslValidator extends AbstractBDslValidator {

    @Check
    def checkEntityDefinition(EntityDefinition e) {
        // with aerospike, indexes must be single column...
        if (e.provider == StorageProvider.AEROSPIKE) {
            for (i : e.indexes) {
                if (i.isIsUnique)
                    error('''nonunique indexes supported only for Aerospike''', BDslPackage.Literals.ENTITY_DEFINITION__PROVIDER)
                else if (i.name === null)
                    error('''indexes must have a name for Aerospike''', BDslPackage.Literals.ENTITY_DEFINITION__PROVIDER)
                else if (i.columns.columnName.size > 1)
                    error('''only single column indexes supported currently for Aerospike''', BDslPackage.Literals.ENTITY_DEFINITION__PROVIDER)
            }
        } else {
            // non Aerospike
            val ref = e.pojoType.extendsClass?.classRef 
            if (ref === null) {
                error('''POJO must inherit from some Ref''', BDslPackage.Literals.ENTITY_DEFINITION__POJO_TYPE)
            } else {
                val grandfather = ref.extendsClass?.classRef
                if (grandfather === null) {
                    error('''POJO must inherit from some Ref which inherits from Ref''', BDslPackage.Literals.ENTITY_DEFINITION__POJO_TYPE)
                }
            }
            if (e.pk.columnName.size != 1)
                    error('''primary key must be a single field''', BDslPackage.Literals.ENTITY_DEFINITION__PK)
//            if (e.tableCategory.trackingColumns === null) {
//                error('''category must specify tracking columns''', BDslPackage.Literals.ENTITY_DEFINITION__TABLE_CATEGORY)
//            }
        }
    }
}
