/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.noSQL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BDslUiModule extends de.jpaw.bonaparte.noSQL.ui.AbstractBDslUiModule {
	public BDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
