/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dts.dsl.ui.contentassist

import de.jpaw.bonaparte.dts.dsl.ui.contentassist.AbstractBDtsProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BDtsProposalProvider extends AbstractBDtsProposalProvider {
}
