/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.jpa.dsl;

// import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;

import org.apache.log4j.Logger;

import de.jpaw.bonaparte.dsl.generator.CommentConverter;
import de.jpaw.bonaparte.jpa.dsl.scoping.BDDLScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDDLRuntimeModule extends de.jpaw.bonaparte.jpa.dsl.AbstractBDDLRuntimeModule {
    private static Logger LOGGER = Logger.getLogger(BDDLRuntimeModule.class);
    public BDDLRuntimeModule() {
        LOGGER.info("BDDL Runtime module constructed");
    }

    @Override
    public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
        LOGGER.info("BON Value converter bound for BDDL");
        return CommentConverter.class;
    }

    // must bind my subclass of ImportedNamespaceAwareScopeProvider here!
    // for implicit importedNamespace
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
        LOGGER.info("BDDL scope provider bound");
        return BDDLScopeProvider.class;
    }

    // bind global scope provider for importURI
    /*
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
        return ImportUriGlobalScopeProvider.class;
    } */
}
