/*
 * generated by Xtext 2.13.0
 */
package de.jpaw.bonaparte.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BonScriptUiModule extends AbstractBonScriptUiModule {
    def Class<? extends org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
        return BonScriptConfiguration;
    }
}
