/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dts.dsl.validation

import de.jpaw.bonaparte.dsl.bonScript.ClassDefinition
import de.jpaw.bonaparte.dts.dsl.bDts.TsClassDefinition
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BDtsValidator extends AbstractBDtsValidator {

    def void checkParentOf(ClassDefinition parent, ClassDefinition of, String msg, EReference whereIsTheProblem) {
        var e = parent
        while (e !== null) {
            if (e === of)
                return;
            e = e.extendsClass?.classRef
        }
        error(msg, whereIsTheProblem)
    }

    @Check
    def checkEntityDefinition(TsClassDefinition e) {
        // with aerospike, indexes must be single column...
    }
}
