/*
* generated by Xtext
*/
package de.jpaw.bonaparte.jpa.dsl.ui.contentassist;

import de.jpaw.bonaparte.jpa.dsl.ui.contentassist.AbstractBDDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BDDLProposalProvider extends AbstractBDDLProposalProvider {

}
