/*
* generated by Xtext
*/
package de.jpaw.bonaparte.dsl.ui.contentassist;

import de.jpaw.bonaparte.dsl.ui.contentassist.AbstractBonScriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BonScriptProposalProvider extends AbstractBonScriptProposalProvider {

}
