/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.dts.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDtsRuntimeModule extends de.jpaw.bonaparte.dts.dsl.AbstractBDtsRuntimeModule {

}
