/*
* generated by Xtext
*/
package de.jpaw.bonaparte.dts.dsl;


/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class BDtsStandaloneSetup extends BDtsStandaloneSetupGenerated{

    public static void doSetup() {
        new BDtsStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
