/*
* generated by Xtext
*/
package de.jpaw.bonaparte.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BonScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
    
}
